import { Template } from './types/template'

export const nyanCat: Template = {
  art: [
    '                  BBBBBBBBBBBBBBBBB       ',
    '                 B-----------------B      ',
    '                B--**************---B     ',
    '    rrrr    rrrrB--******@**@*****--B     ',
    'rrrrrrrrrrrrrrrrB-**@**************-B     ',
    'rrrroooorrrrooooB-**********BB*@***-B BB  ',
    'ooooooooooooooooB-*********B..B****-BB..B ',
    'ooooyyyyooBBBByyB-******@**B...B***-B...B ',
    'yyyyyyyyyyB..BByB-*********B....BBBB....B ',
    'yyyyggggyyBB..BBB-***@*****B............B ',
    'gggggggggggBB..BB-********B..............B',
    'ggggbbbbggggBB..B-*@******B...^B.....^B..B',
    'bbbbbbbbbbbbbBBBB-******@*B...BB...B.BB..B',
    'bbbbmmmmbbbbmmmBB-********B.**.........**B',
    'mmmmmmmmmmmmmmmmB--*@*****B.**.B..B..B.**B',
    'mmmm    mmmm    B---*******B...BBBBBBB..B ',
    '               BBB----------B..........B  ',
    '              B...BBBBBBBBBBBBBBBBBBBBB   ',
    '              B..BB B..B     B..B B..B    ',
    '              BBBBB BBB       BBB  BB     ',
  ],
  pallete: {
    r: '#ff0000',
    o: '#ffa500',
    y: '#ffff00',
    g: '#00ff00',
    b: '#5555ff',
    m: '#990099',
    B: '#000000',
    '.': '#dddddd',
    '-': '#ffffaa',
    '*': '#ff88ee',
    '@': '#bb0099',
    '^': '#ffffff',
  },
}
